# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1786WEyGLwcQ-HaD-snWT9jLcam8cUVAf
"""

import requests
from bs4 import BeautifulSoup

url = 'http://cyberjournalist.org.in/majithia/aicpi_2001.php'
page = requests.get(url)
soup = BeautifulSoup(page.content, "html.parser")
table = soup.findAll(lambda tag: tag.name=='table')
cells = table[1].find_all('td')
flag = False
cpi = []
for cell in cells:
  x = cell.renderContents().decode("utf-8")
  if(flag):
    try:
      cpi.append(float(x))
    except:
      break
  if(x=='<b>2021</b>'):
    flag = True
c,sum=0,0
for i in range(len(cpi)-1,0,-1):
  if(c<3):
    sum = sum+cpi[i]
    c=c+1
  else:
    break
da = (((sum/3)/277.33)-1)*100
print('DA on the basis of last three months = ',da)

print(type(table))

print(table.to_list())